[workspace]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "csvtab"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
run = "mojo main.mojo"

[dependencies]
mojo = ">=1.0.0b1,<1.0.0b2"
slight = { path = "../../" }
